alter table miembro_cargo_relacion drop foreign key FK95EEE5347763C0DA;
alter table miembro_cargo_relacion drop foreign key FK95EEE5343ECEA639;
alter table user_role drop foreign key FK143BF46AC783A11A;
alter table user_role drop foreign key FK143BF46A6CAE64FA;
drop table if exists app_user;
drop table if exists cargos;
drop table if exists miembro;
drop table if exists miembro_cargo_relacion;
drop table if exists role;
drop table if exists user_role;
create table app_user (id bigint not null auto_increment, version integer not null, username varchar(50) not null unique, password varchar(255) not null, password_hint varchar(255), first_name varchar(50) not null, last_name varchar(50) not null, email varchar(255) not null unique, phone_number varchar(255), website varchar(255), address varchar(150), city varchar(50) not null, province varchar(100), country varchar(100), postal_code varchar(15) not null, account_enabled char(1), account_expired char(1) not null, account_locked char(1) not null, credentials_expired char(1) not null, primary key (id)) type=InnoDB;
create table cargos (id integer not null, version integer not null, nombre varchar(100) not null, descripcion varchar(150) not null, primary key (id)) type=InnoDB;
create table miembro (id integer not null, version integer not null, nombre varchar(30) not null, ap_materno varchar(30) not null, ap_paterno varchar(30) not null, sexo varchar(1) not null, estado_civil varchar(2) not null, conyuge varchar(200), tel_fijo varchar(12), tel_cel varchar(13), email varchar(150), observaciones varchar(200), lugar_bautismo varchar(200), ministroOficiante varchar(255), religion_anterior varchar(250), modo_ingreso varchar(2) not null, curso_biblico varchar(100), como_conocio varchar(250), status varchar(2) not null, estudio_creencias varchar(1) not null, diezmando varchar(1), fecha_bautismo datetime not null, fecha_juntaAdm datetime not null, fecha_juntaDir datetime not null, votos_juntaAdm integer not null, votos_juntaDir integer not null, primary key (id)) type=InnoDB;
create table miembro_cargo_relacion (id integer not null, version integer not null, miembro_id integer not null, cargo_id integer not null, fechaInicial datetime not null, fechaFinal datetime not null, primary key (id)) type=InnoDB;
create table role (id bigint not null auto_increment, name varchar(20), description varchar(64), primary key (id)) type=InnoDB;
create table user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) type=InnoDB;
alter table miembro_cargo_relacion add index FK95EEE5347763C0DA (miembro_id), add constraint FK95EEE5347763C0DA foreign key (miembro_id) references miembro (id);
alter table miembro_cargo_relacion add index FK95EEE5343ECEA639 (cargo_id), add constraint FK95EEE5343ECEA639 foreign key (cargo_id) references cargos (id);
alter table user_role add index FK143BF46AC783A11A (role_id), add constraint FK143BF46AC783A11A foreign key (role_id) references role (id);
alter table user_role add index FK143BF46A6CAE64FA (user_id), add constraint FK143BF46A6CAE64FA foreign key (user_id) references app_user (id);
