package mx.edu.um.cargos.webapp.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionMapping;
import mx.edu.um.webapp.form.BaseForm;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="cargoForm" 
 */
public class CargoForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String version;

    protected String nombre;

    protected String descripcion;

    /** Default empty constructor. */
    public CargoForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getVersion()
    {
        return this.version;
    }
   /**
    */

    public void setVersion( String version )
    {
        this.version = version;
    }

    public String getNombre()
    {
        return this.nombre;
    }
   /**
    * @struts.validator type="required"
    */

    public void setNombre( String nombre )
    {
        this.nombre = nombre;
    }

    public String getDescripcion()
    {
        return this.descripcion;
    }
   /**
    * @struts.validator type="required"
    */

    public void setDescripcion( String descripcion )
    {
        this.descripcion = descripcion;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-CargoForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
