package mx.edu.um.miembros.webapp.form;

import javax.servlet.http.HttpServletRequest;

import mx.edu.um.webapp.form.BaseForm;

import org.apache.struts.action.ActionMapping;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="miembroForm" 
 */
public class MiembroForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String version;

    protected String nombre;

    protected String apellidoMaterno;

    protected String apellidoPaterno;

    protected String sexo;

    protected String estadoCivil;

    protected String nombreConyuge;

    protected String telefonoFijo;

    protected String telefonoCelular;

    protected String correoElectronico;

    protected String observaciones;

    protected String lugarBautismo;

    protected String ministroOficiante;

    protected String religionAnterior;

    protected String modoIngreso;

    protected String cursoBiblico;

    protected String comoConocioIglesia;

    protected String status;

    protected String estudioVeintiochoCreencias;

    protected String diezmando;

    protected String fechaBautismo;

    protected String fechaJuntaAdministrativa;

    protected String fechaJuntaDirectiva;

    protected String numeroVotosJuntaAdministrativa;

    protected String numeroVotosJuntaDirectiva;

    protected String nombreCompleto;

    /** Default empty constructor. */
    public MiembroForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getVersion()
    {
        return this.version;
    }
   /**
    */

    public void setVersion( String version )
    {
        this.version = version;
    }

    public String getNombre()
    {
        return this.nombre;
    }
   /**
    * @struts.validator type="required"
    */

    public void setNombre( String nombre )
    {
        this.nombre = nombre;
    }

    public String getApellidoMaterno()
    {
        return this.apellidoMaterno;
    }
   /**
    * @struts.validator type="required"
    */

    public void setApellidoMaterno( String apellidoMaterno )
    {
        this.apellidoMaterno = apellidoMaterno;
    }

    public String getApellidoPaterno()
    {
        return this.apellidoPaterno;
    }
   /**
    * @struts.validator type="required"
    */

    public void setApellidoPaterno( String apellidoPaterno )
    {
        this.apellidoPaterno = apellidoPaterno;
    }

    public String getSexo()
    {
        return this.sexo;
    }
   /**
    * @struts.validator type="required"
    */

    public void setSexo( String sexo )
    {
        this.sexo = sexo;
    }

    public String getEstadoCivil()
    {
        return this.estadoCivil;
    }
   /**
    * @struts.validator type="required"
    */

    public void setEstadoCivil( String estadoCivil )
    {
        this.estadoCivil = estadoCivil;
    }

    public String getNombreConyuge()
    {
        return this.nombreConyuge;
    }
   /**
    */

    public void setNombreConyuge( String nombreConyuge )
    {
        this.nombreConyuge = nombreConyuge;
    }

    public String getTelefonoFijo()
    {
        return this.telefonoFijo;
    }
   /**
    */

    public void setTelefonoFijo( String telefonoFijo )
    {
        this.telefonoFijo = telefonoFijo;
    }

    public String getTelefonoCelular()
    {
        return this.telefonoCelular;
    }
   /**
    */

    public void setTelefonoCelular( String telefonoCelular )
    {
        this.telefonoCelular = telefonoCelular;
    }

    public String getCorreoElectronico()
    {
        return this.correoElectronico;
    }
   /**
    */

    public void setCorreoElectronico( String correoElectronico )
    {
        this.correoElectronico = correoElectronico;
    }

    public String getObservaciones()
    {
        return this.observaciones;
    }
   /**
    */

    public void setObservaciones( String observaciones )
    {
        this.observaciones = observaciones;
    }

    public String getLugarBautismo()
    {
        return this.lugarBautismo;
    }
   /**
    * @struts.validator type="required"
    */

    public void setLugarBautismo( String lugarBautismo )
    {
        this.lugarBautismo = lugarBautismo;
    }

    public String getMinistroOficiante()
    {
        return this.ministroOficiante;
    }
   /**
    * @struts.validator type="required"
    */

    public void setMinistroOficiante( String ministroOficiante )
    {
        this.ministroOficiante = ministroOficiante;
    }

    public String getReligionAnterior()
    {
        return this.religionAnterior;
    }
   /**
    * @struts.validator type="required"
    */

    public void setReligionAnterior( String religionAnterior )
    {
        this.religionAnterior = religionAnterior;
    }

    public String getModoIngreso()
    {
        return this.modoIngreso;
    }
   /**
    * @struts.validator type="required"
    */

    public void setModoIngreso( String modoIngreso )
    {
        this.modoIngreso = modoIngreso;
    }

    public String getCursoBiblico()
    {
        return this.cursoBiblico;
    }
   /**
    */

    public void setCursoBiblico( String cursoBiblico )
    {
        this.cursoBiblico = cursoBiblico;
    }

    public String getComoConocioIglesia()
    {
        return this.comoConocioIglesia;
    }
   /**
    * @struts.validator type="required"
    */

    public void setComoConocioIglesia( String comoConocioIglesia )
    {
        this.comoConocioIglesia = comoConocioIglesia;
    }

    public String getStatus()
    {
        return this.status;
    }
   /**
    */

    public void setStatus( String status )
    {
        this.status = status;
    }

    public String getEstudioVeintiochoCreencias()
    {
        return this.estudioVeintiochoCreencias;
    }
   /**
    * @struts.validator type="required"
    */

    public void setEstudioVeintiochoCreencias( String estudioVeintiochoCreencias )
    {
        this.estudioVeintiochoCreencias = estudioVeintiochoCreencias;
    }

    public String getDiezmando()
    {
        return this.diezmando;
    }
   /**
    */

    public void setDiezmando( String diezmando )
    {
        this.diezmando = diezmando;
    }

    public String getFechaBautismo()
    {
        return this.fechaBautismo;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFechaBautismo( String fechaBautismo )
    {
        this.fechaBautismo = fechaBautismo;
    }

    public String getFechaJuntaAdministrativa()
    {
        return this.fechaJuntaAdministrativa;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFechaJuntaAdministrativa( String fechaJuntaAdministrativa )
    {
        this.fechaJuntaAdministrativa = fechaJuntaAdministrativa;
    }

    public String getFechaJuntaDirectiva()
    {
        return this.fechaJuntaDirectiva;
    }
   /**
    * @struts.validator type="required"
    */

    public void setFechaJuntaDirectiva( String fechaJuntaDirectiva )
    {
        this.fechaJuntaDirectiva = fechaJuntaDirectiva;
    }

    public String getNumeroVotosJuntaAdministrativa()
    {
        return this.numeroVotosJuntaAdministrativa;
    }
   /**
    * @struts.validator type="required"
    */

    public void setNumeroVotosJuntaAdministrativa( String numeroVotosJuntaAdministrativa )
    {
        this.numeroVotosJuntaAdministrativa = numeroVotosJuntaAdministrativa;
    }

    public String getNumeroVotosJuntaDirectiva()
    {
        return this.numeroVotosJuntaDirectiva;
    }
   /**
    * @struts.validator type="required"
    */

    public void setNumeroVotosJuntaDirectiva( String numeroVotosJuntaDirectiva )
    {
        this.numeroVotosJuntaDirectiva = numeroVotosJuntaDirectiva;
    }

        /* To add non XDoclet-generated methods, create a file named
           xdoclet-MiembroForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
