package mx.edu.um.miembros.webapp.form;

import javax.servlet.http.HttpServletRequest;

import mx.edu.um.webapp.form.BaseForm;

import org.apache.struts.action.ActionMapping;

/**
 * Generated by XDoclet/actionform. This class can be further processed with XDoclet/webdoclet/strutsconfigxml and XDoclet/webdoclet/strutsvalidationxml.
 *
 * @struts.form name="miembroCargoRelacionForm" 
 */
public class MiembroCargoRelacionForm
    extends    BaseForm
    implements java.io.Serializable
{

    protected String id;

    protected String version;

    protected String miembroId ;

    protected String cargoId;

    protected String fechaInicial;

    protected String fechaFinal;

    /** Default empty constructor. */
    public MiembroCargoRelacionForm() {}

    public String getId()
    {
        return this.id;
    }
   /**
    */

    public void setId( String id )
    {
        this.id = id;
    }

    public String getVersion()
    {
        return this.version;
    }
   /**
    */

    public void setVersion( String version )
    {
        this.version = version;
    }

    public String getFechaInicial()
    {
        return this.fechaInicial;
    }
    
   /**
    * @struts.validator type="required"
    */
    public void setFechaInicial( String fechaInicial )
    {
        this.fechaInicial = fechaInicial;
    }

    public String getFechaFinal()
    {
        return this.fechaFinal;
    }
    
   /**
    * @struts.validator type="required"
    */
    public void setFechaFinal( String fechaFinal )
    {
        this.fechaFinal = fechaFinal;
    }
    
	public String getMiembroId() {
		return miembroId;
	}
	
	public void setMiembroId(String miembroId) {
		this.miembroId = miembroId;
	}
	
	public String getCargoId() {
		return cargoId;
	}
	
	public void setCargoId(String cargoId) {
		this.cargoId = cargoId;
	}

	/* To add non XDoclet-generated methods, create a file named
           xdoclet-MiembroCargoRelacionForm.java 
           containing the additional code and place it in your metadata/web directory.
        */
    /**
     * @see org.apache.struts.action.ActionForm#reset(org.apache.struts.action.ActionMapping,
     *                                                javax.servlet.http.HttpServletRequest)
     */
    public void reset(ActionMapping mapping, HttpServletRequest request) {
        // reset any boolean data types to false

    }

}
